### PR TITLE
Big fix collection

### PR DESCRIPTION
**Pull request by mrclay**
Let me know which of these commits you're interested in.

### CODE REVIEW

**Comment by mrclay** [comment]
cc @beck24 @juho-jaakkola

**Comment by juho-jaakkola** [comment]
Overriding the action is actually useless because ```NotificationsService::sendNotification()``` doesn't support sending notifications to the owner. I've never used that feature, so I hadn't noticed this flaw until now.

**Comment by juho-jaakkola** [comment]
Following likes is kind of out of the scope of the plugin.

**Comment by juho-jaakkola** [comment]
The river menu item might work.

**Comment by juho-jaakkola** [comment]
Cleanup/optimizations is always welcome.

**Comment by juho-jaakkola** [comment]
Language improvements are also good.

**Comment by mrclay** [comment]
You mean auto-subscribe when you like something should be a separate plugin?

**Comment by mrclay** [comment]
I could make subscribe-when-I-like-something a default-off option.

Subscribe links in river seems like it should be a site option (default off for BC). Actually same with entity menu (default on).

**Comment by juho-jaakkola** [comment]
> You mean auto-subscribe when you like something should be a separate plugin?

Sorry, I misunderstood this. I though you wanted to follow both comments *and* likes. The like-button doing the same as the subscribe-button seems like an OK idea.

**Comment by mrclay** [comment]
Only bummer is there's no good way to toggle the subscribe on like. You have to wait for the likes XHR response to come back and re-check the subscribed state server-side (the user may have manually unsubbed before).

**Comment by beck24** [comment]
Have either of you looked at the CT subscribed content plugin?  Jeroen asked if we'd be interested in putting our efforts together in a standardized core version.  I think that makes sense.

**Comment by mrclay** [comment]
From a not-terribly-deep review of the code it looks like the same stuff, though using direct `notifyMETHOD` relationships. I prefer this way.

**Comment by beck24** [comment]
I haven't looked at their code on it yet.  I figured if we go that route we'd have to pick either this plugin or theirs to use as the base.  Without any knowledge of theirs I assumed theirs might be better, as this started off as a poorly written 1.7 plugin that I upgraded for compatibility.  There is/was still a lot of legacy code that should be cleaned up (though I think Juho took care of some of that bringing it up to 1.9?).

**Pull request closed without merging**
